/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PhotographyRouteImport } from './routes/photography'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as ContentIndexRouteImport } from './routes/content.index'
import { Route as ContentSlugRouteImport } from './routes/content.$slug'
import { Route as ContributorsIndexRouteImport } from './routes/contributors.index'
import { Route as ContributorsSlugRouteImport } from './routes/contributors.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyRoute = PhotographyRouteImport.update({
  id: '/photography',
  path: '/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentIndexRoute = ContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentSlugRoute = ContentSlugRouteImport.update({
  id: '/content/$slug',
  path: '/content/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorsIndexRoute = ContributorsIndexRouteImport.update({
  id: '/contributors/',
  path: '/contributors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorsSlugRoute = ContributorsSlugRouteImport.update({
  id: '/contributors/$slug',
  path: '/contributors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/photography': typeof PhotographyRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/content/$slug': typeof ContentSlugRoute
  '/contributors/$slug': typeof ContributorsSlugRoute
  '/content/': typeof ContentIndexRoute
  '/contributors/': typeof ContributorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/photography': typeof PhotographyRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/content/$slug': typeof ContentSlugRoute
  '/contributors/$slug': typeof ContributorsSlugRoute
  '/content': typeof ContentIndexRoute
  '/contributors': typeof ContributorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/photography': typeof PhotographyRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/content/$slug': typeof ContentSlugRoute
  '/contributors/$slug': typeof ContributorsSlugRoute
  '/content/': typeof ContentIndexRoute
  '/contributors/': typeof ContributorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/photography'
    | '/article/$slug'
    | '/content/$slug'
    | '/contributors/$slug'
    | '/content/'
    | '/contributors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/photography'
    | '/article/$slug'
    | '/content/$slug'
    | '/contributors/$slug'
    | '/content'
    | '/contributors'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/photography'
    | '/article/$slug'
    | '/content/$slug'
    | '/contributors/$slug'
    | '/content/'
    | '/contributors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PhotographyRoute: typeof PhotographyRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  ContentSlugRoute: typeof ContentSlugRoute
  ContributorsSlugRoute: typeof ContributorsSlugRoute
  ContentIndexRoute: typeof ContentIndexRoute
  ContributorsIndexRoute: typeof ContributorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography': {
      id: '/photography'
      path: '/photography'
      fullPath: '/photography'
      preLoaderRoute: typeof PhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/': {
      id: '/content/'
      path: '/content'
      fullPath: '/content/'
      preLoaderRoute: typeof ContentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$slug': {
      id: '/content/$slug'
      path: '/content/$slug'
      fullPath: '/content/$slug'
      preLoaderRoute: typeof ContentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributors/': {
      id: '/contributors/'
      path: '/contributors'
      fullPath: '/contributors/'
      preLoaderRoute: typeof ContributorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributors/$slug': {
      id: '/contributors/$slug'
      path: '/contributors/$slug'
      fullPath: '/contributors/$slug'
      preLoaderRoute: typeof ContributorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PhotographyRoute: PhotographyRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  ContentSlugRoute: ContentSlugRoute,
  ContributorsSlugRoute: ContributorsSlugRoute,
  ContentIndexRoute: ContentIndexRoute,
  ContributorsIndexRoute: ContributorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
