// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knfzuslaeqfxrtiypokf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtuZnp1c2xhZXFmeHJ0aXlwb2tmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYwMDczMzMsImV4cCI6MjEwMTU4MzMzM30.V_KffFugzvbOZq7mZ-zg5YJ2lTGQcK6K6UnRBMs84Eg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});